//Courses
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';

//Products
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const START_LOADING_PRODUCTS = 'START_LOADING_PRODUCTS';
export const LOADING_PRODUCTS_DONE = 'LOADING_PRODUCTS_DONE';